### ISSUE TITLE
Provide a Signed Nuget Package

### ISSUE THREAD

**Issue by Sebbstar** [sonicjolt/serilog-sinks-rabbitmq#74]
**Is your feature request related to a problem? Please describe.**
We can only use signed packages.
When using Serilog.Sinks.RabbitMq we've got following exception:

`FileLoadException: Could not load file or assembly 'Serilog.Sinks.RabbitMQ, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044)`

**Describe the solution you'd like**
Provide a signed package

**Comment by sonicjolt** [comment]
I agree that we should sign the nuget package. I will look into what needs to be done to get that done.

**Comment by sonicjolt** [comment]
Based on discussion: https://jeremydmiller.com/2014/04/28/fubumvc-lessons-learned-strong-naming-woes-and-workarounds/ I don't think it is a good idea to add strong naming to this library. 

If strong naming is needed I suggest that you build your own nuget-package, and sign it yourself. The nuget package is provided for ease of use of this library - and something that users of the software can easily do by themselves. And since the requirement of signed packages is something probably required by your organisation, I will leave it up to your organisation to deal with the reprecussions of that decision.

But thanks for the suggestion - I learned something researching this.
